name: CI

on:
  push:
  pull_request:

jobs:
  build-all-targets:
    name: Build all targets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./scripts/build-all-targets.sh --verbose
    - run: ./scripts/build-all-targets.sh --verbose --no-default-features
    - run: ./scripts/build-all-targets.sh --verbose --no-default-features --features std

  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup component add rustfmt
    - run: ./scripts/check-formatting.sh --verbose

  generate-documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./scripts/generate-documentation.sh --verbose

  measure-code-coverage:
    name: Measure code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-llvm-cov
    - run: ./scripts/measure-code-coverage.sh --verbose

  run-all-examples-under-miri:
    name: Run all examples under Miri
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
    - run: ./scripts/run-all-examples-under-miri.sh --verbose

  run-all-examples:
    name: Run all examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./scripts/run-all-examples.sh --verbose

  run-all-tests-under-miri:
    name: Run all tests under Miri
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
    - run: ./scripts/run-all-tests-under-miri.sh --verbose

  run-all-tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./scripts/run-all-tests.sh --verbose
    - run: ./scripts/run-all-tests.sh --verbose --release

  run-clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup component add clippy
    - run: ./scripts/run-clippy.sh
